[package]
name = "basic-transpilation-prime"
version = "0.1.0"
authors = ["arbaregni <jamesnsours@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "*"
pest_derive = "2.1.0"
fstrings = "0.2.2"